services:
  paperless-rest:
    build:
      context: ./PaperlessREST
      dockerfile: Dockerfile
    ports:
      - 8081:8081

  paperless-ui:
    build:
      context: ./PaperlessNginxUi
      dockerfile: Dockerfile
    ports:
      - 80:80
