services:
  paperless-rest:
    build:
      context: ./PaperlessREST
      dockerfile: Dockerfile
    image: paperless-rest
    ports:
      - 8080:8080
    container_name: paperless-rest
    # todo new build when changes happened
