services:
  paperless-rest:
    build:
      context: ./PaperlessREST
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      paperless-persistence:
        condition: service_healthy

  paperless-ui:
    build:
      context: ./PaperlessUI
      dockerfile: Dockerfile
    ports:
      - 80:80
  
  paperless-persistence:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paperless
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      