services:
  paperless-rest:
    build:
      context: ./PaperlessREST
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      paperless-persistence:
        condition: service_healthy

  paperless-services:
    build:
      context: ./PaperlessServices
      dockerfile: Dockerfile
    ports:
      - 8082:8082

  paperless-ui:
    build:
      context: ./PaperlessUI
      dockerfile: Dockerfile
    ports:
      - 80:80

  paperless-persistence:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paperless
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  MinIO:
    image: minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    entrypoint: sh -c "mkdir -p /data && /usr/bin/docker-entrypoint.sh minio server /data --console-address ':9090'"

  RabbitMQ:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 9093:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmqadmin
      - RABBITMQ_DEFAULT_PASS=rabbitmqadmin