server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://paperless-persistence:5432/paperless
    username: postgres
    password: postgres

  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop # update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  jackson:
    date-format: 'at.fhtw.swkom.paperless.services.RFC3339DateFormat'
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

minio:
  endpoint: http://MinIO:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: documentBucket